// server/services/DiagramIndexReader.js
/**
 * DiagramIndexReader - Reads and organizes indexed diagram elements
 * Index codes are generated by the frontend - this service only reads them
 */

const logger = require('../utils/logger-wrapper');

// Import all valid types from the TypeScript definitions
const VALID_ZONES = [
  'Internet', 'External', 'DMZ', 'Internal', 'Trusted', 'Restricted', 
  'Critical', 'OT', 'Development', 'Staging', 'Production', 'Cloud', 
  'Guest', 'Compliance', 'Management', 'ControlPlane', 'DataPlane', 
  'ServiceMesh', 'BackOffice', 'Partner', 'ThirdParty', 'Quarantine', 
  'Recovery', 'Edge', 'Hybrid', 'MultiCloud'
];

const VALID_NODE_TYPES = {
  infrastructure: [
    'server', 'workstation', 'endpoint', 'printer', 'router', 'switch', 
    'dns', 'gateway'
  ],
  security: [
    'firewall', 'vpnGateway', 'ids', 'ips', 'waf', 'proxy', 'reverseProxy', 
    'monitor', 'siem', 'soar', 'xdr', 'edr', 'ndr', 'casb', 'sase', 'ztna', 
    'dlp', 'dam', 'pam', 'hsm', 'kms', 'secretsManager', 'certificateAuthority', 
    'mfa', 'sso', 'ldap', 'radiusServer', 'honeypot', 'honeynet', 'deceptionSystem', 
    'networkTap', 'packetCapture', 'vulnerabilityScanner', 'patchManagement', 
    'configManagement', 'complianceScanner', 'penTestTool', 'staticAnalysis', 
    'dynamicAnalysis', 'containerScanner', 'k8sAdmissionController', 'meshProxy', 
    'apiSecurity', 'botProtection', 'ddosProtection', 'emailSecurity', 'webFilter', 
    'sandboxAnalyzer', 'threatIntelPlatform', 'forensicsStation', 
    'incidentResponsePlatform', 'backupSystem', 'disasterRecovery', 
    'encryptionGateway', 'tokenizer', 'riskAnalytics', 'identityGovernance', 
    'cloudSecurityPosture', 'workloadProtection', 'runtimeProtection', 
    'supplychainSecurity', 'codeRepository', 'cicdSecurity', 'secretScanner', 
    'sbom', 'dependencyScanner', 'infrastructureAsCode', 'policyAsCode', 
    'cloudAccessBroker', 'remoteAccessGateway', 'bastionHost', 'jumpServer', 
    'aiSecurityGateway', 'quantumKeyDistribution', 'blockchainSecurity', 
    'otSecurityGateway', 'iotSecurityGateway', 'physicalAccessControl', 
    'videoSurveillance', 'securityOrchestrator'
  ],
  application: [
    'application', 'database', 'loadBalancer', 'apiGateway', 
    'webServer', 'authServer', 'messageBroker', 'api', 'service', 'cache', 
    'storage', 'vault', 'identity', 'logging'
  ],
  cloud: [
    'cloudService', 'containerRegistry', 'kubernetesPod', 'kubernetesService', 
    'storageAccount', 'functionApp', 'apiManagement', 'cloudLoadBalancer', 
    'cloudFirewall', 'cloudDatabase'
  ],
  ot: [
    'plc', 'hmi', 'historian', 'rtu', 'sensor', 'actuator', 'scadaServer', 
    'industrialFirewall', 'safetySystem', 'industrialNetwork'
  ],
  ai: [
    'aiModel', 'llmService', 'mlPipeline', 'aiGateway', 'vectorDatabase', 
    'modelRegistry', 'inferenceEngine', 'aiWorkbench', 'dataLake', 
    'featureStore', 'ai'
  ],
  cybercrime: [
    'fraudDetection', 'transactionMonitor', 'antiMalware', 'honeypot', 
    'threatFeed', 'sandboxEnv', 'forensicsWorkstation', 'incidentResponse', 
    'cyberInsurance', 'fraudAnalytics'
  ],
  privacy: [
    'dataClassifier', 'consentManager', 'dataMapper', 'privacyScanner', 
    'dataRetention', 'dataAnonymizer', 'gdprCompliance', 'dataBreach', 
    'privacyImpact', 'dataSubjectRights'
  ],
  appSec: [
    'memoryPool', 'executionContext', 'sessionStore', 'inputBuffer', 
    'outputBuffer', 'configManager', 'cryptoModule', 'tokenValidator', 
    'permissionEngine', 'auditLogger'
  ],
  redTeam: [
    'attackBox', 'payloadServer', 'c2Server', 'implant', 'phishingServer', 
    'exfilChannel', 'pivotPoint', 'credentialHarvester', 'lateralMovement', 
    'persistenceMechanism'
  ],
  special: ['securityZone', 'generic']
};

class DiagramIndexReader {
  constructor() {
    this.reset();
    this.initializeMappings();
  }
  
  reset() {
    // Core indexes
    this.nodeIndex = new Map();        // nodeId -> node object
    this.edgeIndex = new Map();        // edgeId -> edge object
    this.zoneIndex = new Map();        // zoneType -> Set of nodeIds
    this.typeIndex = new Map();        // nodeType -> Set of nodeIds
    
    // Relationship indexes
    this.nodeConnections = new Map();  // nodeId -> { inbound: Set, outbound: Set }
    this.zoneConnections = new Map();  // zoneType -> { internal: Set, inbound: Set, outbound: Set }
    
    // Reference mappings
    this.nodeToCode = new Map();       // nodeId -> alphanumeric code
    this.codeToNode = new Map();       // alphanumeric code -> nodeId
    this.edgeToCode = new Map();       // edgeId -> alphanumeric edge code
    this.codeToEdge = new Map();       // alphanumeric edge code -> edgeId
    this.labelToNodes = new Map();     // lowercase label -> Set of nodeIds
    
    
    // Metadata
    this.statistics = {
      totalNodes: 0,
      totalEdges: 0,
      nodesByType: {},
      nodesByZone: {},
      crossZoneConnections: 0,
      unencryptedConnections: 0
    };
  }
  
  initializeMappings() {
    // Create reverse mappings for quick lookups
    this.nodeTypeMap = new Map();
    this.nodeTypeCategory = new Map();
    
    Object.entries(VALID_NODE_TYPES).forEach(([category, types]) => {
      types.forEach(type => {
        this.nodeTypeMap.set(type.toLowerCase(), type);
        this.nodeTypeCategory.set(type, category);
      });
    });
    
    this.zoneMap = new Map();
    VALID_ZONES.forEach(zone => {
      this.zoneMap.set(zone.toLowerCase(), zone);
    });
  }
  
  /**
   * Index a complete diagram
   */
  indexDiagram(diagram) {
    if (!diagram || !diagram.nodes) {
      logger.warn('DiagramIndexReader: No diagram data to read');
      return this;
    }
    
    this.reset();
    
    
    // Sort non-zone and non-drawing nodes by id for deterministic index codes matching frontend
    const nonZoneNodes = diagram.nodes.filter(n => 
      n.type !== 'securityZone' && 
      n.type !== 'freehand' && 
      n.type !== 'shape' && 
      n.type !== 'textAnnotation'
    );
    nonZoneNodes.sort((a,b)=> a.id.localeCompare(b.id));
    nonZoneNodes.forEach(node => this.indexNode(node));

    // Index zone containers afterwards so they are still available in main index
    diagram.nodes.filter(n=> n.type === 'securityZone').forEach(node=> this.indexNode(node));
    
    // Then index all edges
    if (diagram.edges) {
      diagram.edges.forEach(edge => this.indexEdge(edge, diagram.nodes));
    }
    
    // Calculate statistics
    this.calculateStatistics();
    
    logger.info('Diagram indexed:', this.statistics);
    return this;
  }
  
  /**
   * Index a single node
   */
  indexNode(node) {
    if (!node || !node.id) return;
    
    // Skip securityZone nodes - they're just visual containers
    if (node.type === 'securityZone') {
      return;
    }
    
    // Skip drawing nodes - they're not included in analysis
    if (node.type === 'freehand' || node.type === 'shape' || node.type === 'textAnnotation') {
      return;
    }
    
    const nodeId = node.id;
    const nodeType = node.type;
    const nodeData = node.data || {};
    
    // Store in main index
    this.nodeIndex.set(nodeId, node);
    
    // Read existing index code from frontend
    const code = node.data?.indexCode;
    if (!code) {
      logger.warn(`DiagramIndexReader: Node ${nodeId} (${nodeData.label}) missing index code`);
      // Use a fallback but don't generate
      const fallbackCode = `${nodeType.substring(0, 3).toUpperCase()}-UNKNOWN-${nodeId.substring(0, 3)}`;
      this.nodeToCode.set(nodeId, fallbackCode);
      this.codeToNode.set(fallbackCode, nodeId);
      return;
    }
    
    this.nodeToCode.set(nodeId, code);
    this.codeToNode.set(code, nodeId);
    
    // Index by type
    if (!this.typeIndex.has(nodeType)) {
      this.typeIndex.set(nodeType, new Set());
    }
    this.typeIndex.get(nodeType).add(nodeId);
    
    // Index by zone (if not a zone node itself)
    if (nodeType !== 'securityZone' && nodeData.zone) {
      const zone = this.normalizeZone(nodeData.zone);
      if (!this.zoneIndex.has(zone)) {
        this.zoneIndex.set(zone, new Set());
      }
      this.zoneIndex.get(zone).add(nodeId);
    }
    
    // Index by label for text search
    if (nodeData.label) {
      const labelLower = nodeData.label.toLowerCase();
      if (!this.labelToNodes.has(labelLower)) {
        this.labelToNodes.set(labelLower, new Set());
      }
      this.labelToNodes.get(labelLower).add(nodeId);
      
      // Also index partial matches (e.g., "app server" -> ["app", "server"])
      const words = labelLower.split(/\s+/);
      words.forEach(word => {
        if (word.length > 2) { // Skip very short words
          if (!this.labelToNodes.has(word)) {
            this.labelToNodes.set(word, new Set());
          }
          this.labelToNodes.get(word).add(nodeId);
        }
      });
    }
    
    // Initialize connection tracking
    this.nodeConnections.set(nodeId, {
      inbound: new Set(),
      outbound: new Set()
    });
  }
  
  /**
   * Index a single edge
   */
  indexEdge(edge, allNodes) {
    if (!edge || !edge.id) return;
    
    const edgeId = edge.id;
    const sourceId = edge.source;
    const targetId = edge.target;
    
    // Store in main index
    this.edgeIndex.set(edgeId, edge);
    
    // Read existing edge code from frontend
    const edgeCode = edge.data?.indexCode;
    if (!edgeCode) {
      logger.warn(`DiagramIndexReader: Edge ${edgeId} missing index code`);
      // Use a fallback but don't generate
      const fallbackCode = `edge-${edgeId}`;
      this.edgeToCode.set(edgeId, fallbackCode);
      this.codeToEdge.set(fallbackCode, edgeId);
      return;
    }
    
    this.edgeToCode.set(edgeId, edgeCode);
    this.codeToEdge.set(edgeCode, edgeId);
    
    // Update node connections
    if (this.nodeConnections.has(sourceId)) {
      this.nodeConnections.get(sourceId).outbound.add(edgeId);
    }
    if (this.nodeConnections.has(targetId)) {
      this.nodeConnections.get(targetId).inbound.add(edgeId);
    }
    
    // Track zone connections
    const sourceNode = this.nodeIndex.get(sourceId);
    const targetNode = this.nodeIndex.get(targetId);
    
    if (sourceNode && targetNode) {
      const sourceZone = sourceNode.data?.zone;
      const targetZone = targetNode.data?.zone;
      
      if (sourceZone && targetZone) {
        // Track cross-zone connections
        if (sourceZone !== targetZone) {
          this.trackZoneConnection(sourceZone, targetZone, edgeId);
        } else {
          // Internal zone connection
          if (!this.zoneConnections.has(sourceZone)) {
            this.zoneConnections.set(sourceZone, {
              internal: new Set(),
              inbound: new Set(),
              outbound: new Set()
            });
          }
          this.zoneConnections.get(sourceZone).internal.add(edgeId);
        }
      }
    }
  }
  


  /**
   * Get a simple label from a node (first word, lowercased, cleaned)
   */
  getSimpleLabel(node) {
    const label = node.data?.label || node.type || 'node';
    
    // Take first word and simplify
    const firstWord = label.toLowerCase().split(/\s+/)[0];
    
    // Handle common multi-word components
    if (label.toLowerCase().includes('database')) return 'db';
    if (label.toLowerCase().includes('server')) return 'server';
    if (label.toLowerCase().includes('service')) return 'service';
    if (label.toLowerCase().includes('gateway')) return 'gateway';
    if (label.toLowerCase().includes('firewall')) return 'firewall';
    if (label.toLowerCase().includes('primary')) return 'primary-db';
    if (label.toLowerCase().includes('backup')) return 'backup-db';
    
    // Clean the first word
    return firstWord.replace(/[^a-z0-9]/g, '').substring(0, 8);
  }

  /**
   * Get a simple handle name (top, bottom, left, right)
   */
  getSimpleHandle(handle) {
    if (!handle) return 'center';
    
    // Handle format is typically like "top", "bottom", "left", "right"
    const handleLower = handle.toLowerCase();
    
    if (handleLower.includes('top')) return 'top';
    if (handleLower.includes('bottom')) return 'bottom';
    if (handleLower.includes('left')) return 'left';
    if (handleLower.includes('right')) return 'right';
    
    return 'center';
  }
  
  /**
   * Track connections between zones
   */
  trackZoneConnection(sourceZone, targetZone, edgeId) {
    // Initialize zone connection tracking if needed
    if (!this.zoneConnections.has(sourceZone)) {
      this.zoneConnections.set(sourceZone, {
        internal: new Set(),
        inbound: new Set(),
        outbound: new Set()
      });
    }
    if (!this.zoneConnections.has(targetZone)) {
      this.zoneConnections.set(targetZone, {
        internal: new Set(),
        inbound: new Set(),
        outbound: new Set()
      });
    }
    
    // Track outbound from source and inbound to target
    this.zoneConnections.get(sourceZone).outbound.add(edgeId);
    this.zoneConnections.get(targetZone).inbound.add(edgeId);
  }
  
  /**
   * Calculate statistics about the indexed diagram
   */
  calculateStatistics() {
    this.statistics.totalNodes = this.nodeIndex.size;
    this.statistics.totalEdges = this.edgeIndex.size;
    
    // Count nodes by type
    this.typeIndex.forEach((nodes, type) => {
      this.statistics.nodesByType[type] = nodes.size;
    });
    
    // Count nodes by zone
    this.zoneIndex.forEach((nodes, zone) => {
      this.statistics.nodesByZone[zone] = nodes.size;
    });
    
    // Count cross-zone connections
    let crossZoneCount = 0;
    let unencryptedCount = 0;
    
    this.edgeIndex.forEach(edge => {
      const source = this.nodeIndex.get(edge.source);
      const target = this.nodeIndex.get(edge.target);
      
      if (source?.data?.zone !== target?.data?.zone) {
        crossZoneCount++;
      }
      
      if (!edge.data?.encryption || edge.data.encryption === 'none') {
        unencryptedCount++;
      }
    });
    
    this.statistics.crossZoneConnections = crossZoneCount;
    this.statistics.unencryptedConnections = unencryptedCount;
  }
  
  /**
   * Normalize zone names for consistent lookups
   */
  normalizeZone(zone) {
    if (!zone) return 'Unknown';
    const normalized = this.zoneMap.get(zone.toLowerCase());
    return normalized || zone;
  }
  
  /**
   * Find nodes by query text using the index
   */
  findNodesByQuery(query) {
    const results = new Set();
    const queryLower = query.toLowerCase();
    const words = queryLower.split(/\s+/);
    
    // Check each word against our indexes
    words.forEach(word => {
      // Check node types
      const nodeType = this.nodeTypeMap.get(word);
      if (nodeType && this.typeIndex.has(nodeType)) {
        this.typeIndex.get(nodeType).forEach(nodeId => results.add(nodeId));
      }
      
      // Check zones
      const zone = this.zoneMap.get(word);
      if (zone && this.zoneIndex.has(zone)) {
        this.zoneIndex.get(zone).forEach(nodeId => results.add(nodeId));
      }
      
      // Check labels
      if (this.labelToNodes.has(word)) {
        this.labelToNodes.get(word).forEach(nodeId => results.add(nodeId));
      }
    });
    
    // Also check for exact label matches
    if (this.labelToNodes.has(queryLower)) {
      this.labelToNodes.get(queryLower).forEach(nodeId => results.add(nodeId));
    }
    
    return Array.from(results);
  }
  
  /**
   * Get all nodes in a specific zone
   */
  getNodesInZone(zone) {
    const normalizedZone = this.normalizeZone(zone);
    return Array.from(this.zoneIndex.get(normalizedZone) || []);
  }
  
  /**
   * Get all nodes of a specific type
   */
  getNodesByType(type) {
    return Array.from(this.typeIndex.get(type) || []);
  }
  
  /**
   * Get node by its alphanumeric code
   */
  getNodeByCode(code) {
    const nodeId = this.codeToNode.get(code);
    return nodeId ? this.nodeIndex.get(nodeId) : null;
  }

  /**
   * Get edge by its alphanumeric code
   */
  getEdgeByCode(code) {
    const edgeId = this.codeToEdge.get(code);
    return edgeId ? this.edgeIndex.get(edgeId) : null;
  }

  /**
   * Get edge code by edge ID
   */
  getEdgeCode(edgeId) {
    return this.edgeToCode.get(edgeId);
  }
  
  /**
   * Get all connections for a node
   */
  getNodeConnections(nodeId) {
    const connections = this.nodeConnections.get(nodeId);
    if (!connections) return { inbound: [], outbound: [] };
    
    return {
      inbound: Array.from(connections.inbound).map(edgeId => this.edgeIndex.get(edgeId)),
      outbound: Array.from(connections.outbound).map(edgeId => this.edgeIndex.get(edgeId))
    };
  }
  
  /**
   * Get connected nodes (1 hop)
   */
  getConnectedNodes(nodeId) {
    const connections = this.getNodeConnections(nodeId);
    const connectedNodes = new Set();
    
    connections.inbound.forEach(edge => {
      if (edge) connectedNodes.add(edge.source);
    });
    
    connections.outbound.forEach(edge => {
      if (edge) connectedNodes.add(edge.target);
    });
    
    // Remove self
    connectedNodes.delete(nodeId);
    
    return Array.from(connectedNodes).map(id => this.nodeIndex.get(id)).filter(Boolean);
  }
  
  /**
   * Get nodes with high security levels or sensitive data
   * Note: Just organizing data, not making security judgments
   */
  getHighValueNodes() {
    const nodes = [];
    
    this.nodeIndex.forEach(node => {
      // Simply collect nodes with certain metadata values
      // The AI will determine what's actually critical
      if (node.data?.securityLevel === 'Maximum' || 
          node.data?.dataClassification === 'Confidential' ||
          (node.data?.securityLevel === 'High' && node.data?.dataClassification === 'Sensitive')) {
        nodes.push(node);
      }
    });
    
    return nodes;
  }
  
  /**
   * Get diagram summary for context
   */
  getDiagramSummary() {
    return {
      statistics: this.statistics,
      zones: Array.from(this.zoneIndex.keys()),
      nodeTypes: Array.from(this.typeIndex.keys()),
      highValueNodes: this.getHighValueNodes().map(n => ({
        id: n.id,
        code: this.nodeToCode.get(n.id),
        label: n.data?.label,
        type: n.type,
        zone: n.data?.zone,
        securityLevel: n.data?.securityLevel,
        dataClassification: n.data?.dataClassification
      })),
      connectionStats: {
        total: this.statistics.totalEdges,
        crossZone: this.statistics.crossZoneConnections,
        unencrypted: this.statistics.unencryptedConnections
      }
    };
  }
  
  /**
   * Add or update a single node in the index
   */
  addOrUpdateNode(node) {
    if (!node || !node.id) return;
    
    // Skip drawing nodes
    if (node.type === 'freehand' || node.type === 'shape' || node.type === 'textAnnotation') {
      return;
    }
    
    // Remove old node if it exists (to update indexes properly)
    if (this.nodeIndex.has(node.id)) {
      this.removeNode(node.id);
    }
    
    // Add the node
    this.indexNode(node);
    
    // Recalculate statistics
    this.calculateStatistics();
    
    logger.info(`Node ${node.id} added/updated in index`);
  }
  
  /**
   * Remove a node from the index
   */
  removeNode(nodeId) {
    const node = this.nodeIndex.get(nodeId);
    if (!node) return;
    
    // Remove from main index
    this.nodeIndex.delete(nodeId);
    
    // Remove from type index
    if (node.type && this.typeIndex.has(node.type)) {
      this.typeIndex.get(node.type).delete(nodeId);
      if (this.typeIndex.get(node.type).size === 0) {
        this.typeIndex.delete(node.type);
      }
    }
    
    // Remove from zone index
    if (node.data?.zone) {
      const zone = this.normalizeZone(node.data.zone);
      if (this.zoneIndex.has(zone)) {
        this.zoneIndex.get(zone).delete(nodeId);
        if (this.zoneIndex.get(zone).size === 0) {
          this.zoneIndex.delete(zone);
        }
      }
    }
    
    // Remove from label index
    if (node.data?.label) {
      const labelLower = node.data.label.toLowerCase();
      if (this.labelToNodes.has(labelLower)) {
        this.labelToNodes.get(labelLower).delete(nodeId);
        if (this.labelToNodes.get(labelLower).size === 0) {
          this.labelToNodes.delete(labelLower);
        }
      }
      
      // Remove partial matches
      const words = labelLower.split(/\s+/);
      words.forEach(word => {
        if (word.length > 2 && this.labelToNodes.has(word)) {
          this.labelToNodes.get(word).delete(nodeId);
          if (this.labelToNodes.get(word).size === 0) {
            this.labelToNodes.delete(word);
          }
        }
      });
    }
    
    // Remove from code mappings
    const code = this.nodeToCode.get(nodeId);
    if (code) {
      this.codeToNode.delete(code);
      this.nodeToCode.delete(nodeId);
    }
    
    // Remove node connections
    this.nodeConnections.delete(nodeId);
    
    // Remove associated edges
    const connections = this.getNodeConnections(nodeId);
    [...connections.inbound, ...connections.outbound].forEach(edge => {
      if (edge) {
        this.removeEdge(edge.id);
      }
    });
    
    // Recalculate statistics
    this.calculateStatistics();
    
    logger.info(`Node ${nodeId} removed from index`);
  }
  
  /**
   * Add or update a single edge in the index
   */
  addOrUpdateEdge(edge, allNodes) {
    if (!edge || !edge.id) return;
    
    // Remove old edge if it exists
    if (this.edgeIndex.has(edge.id)) {
      this.removeEdge(edge.id);
    }
    
    // Add the edge
    this.indexEdge(edge, allNodes);
    
    // Recalculate statistics
    this.calculateStatistics();
    
    logger.info(`Edge ${edge.id} added/updated in index`);
  }
  
  /**
   * Remove an edge from the index
   */
  removeEdge(edgeId) {
    const edge = this.edgeIndex.get(edgeId);
    if (!edge) return;
    
    // Remove from main index
    this.edgeIndex.delete(edgeId);
    
    // Remove from code mappings
    const edgeCode = this.edgeToCode.get(edgeId);
    if (edgeCode) {
      this.codeToEdge.delete(edgeCode);
      this.edgeToCode.delete(edgeId);
    }
    
    // Remove from node connections
    if (this.nodeConnections.has(edge.source)) {
      this.nodeConnections.get(edge.source).outbound.delete(edgeId);
    }
    if (this.nodeConnections.has(edge.target)) {
      this.nodeConnections.get(edge.target).inbound.delete(edgeId);
    }
    
    // Remove from zone connections
    const sourceNode = this.nodeIndex.get(edge.source);
    const targetNode = this.nodeIndex.get(edge.target);
    
    if (sourceNode && targetNode) {
      const sourceZone = sourceNode.data?.zone;
      const targetZone = targetNode.data?.zone;
      
      if (sourceZone && targetZone) {
        if (sourceZone !== targetZone) {
          // Cross-zone connection
          if (this.zoneConnections.has(sourceZone)) {
            this.zoneConnections.get(sourceZone).outbound.delete(edgeId);
          }
          if (this.zoneConnections.has(targetZone)) {
            this.zoneConnections.get(targetZone).inbound.delete(edgeId);
          }
        } else {
          // Internal zone connection
          if (this.zoneConnections.has(sourceZone)) {
            this.zoneConnections.get(sourceZone).internal.delete(edgeId);
          }
        }
      }
    }
    
    // Recalculate statistics
    this.calculateStatistics();
    
    logger.info(`Edge ${edgeId} removed from index`);
  }
  
  /**
   * Check if a label is unique
   */
  isLabelUnique(label, nodeId = null) {
    if (!label) return false;
    
    const labelLower = label.toLowerCase();
    const nodeIds = this.labelToNodes.get(labelLower) || new Set();
    
    // If no nodes have this label, it's unique
    if (nodeIds.size === 0) return true;
    
    // If updating an existing node, check if it's the only one with this label
    if (nodeId && nodeIds.size === 1 && nodeIds.has(nodeId)) {
      return true;
    }
    
    return false;
  }

  /**
   * Find node by exact label match (case-insensitive)
   * Returns the node and its code for internal use
   */
  findNodeByLabel(label, zone = null) {
    if (!label) return null;
    
    const labelLower = label.toLowerCase();
    const nodeIds = this.labelToNodes.get(labelLower) || new Set();
    
    if (nodeIds.size === 0) return null;
    
    // If zone is specified, filter by zone
    if (zone && nodeIds.size > 1) {
      for (const nodeId of nodeIds) {
        const node = this.nodeIndex.get(nodeId);
        if (node && node.data?.zone === zone) {
          return {
            node: node,
            code: this.nodeToCode.get(nodeId)
          };
        }
      }
    }
    
    // Return first match
    const nodeId = nodeIds.values().next().value;
    return {
      node: this.nodeIndex.get(nodeId),
      code: this.nodeToCode.get(nodeId)
    };
  }

  /**
   * Generate a compact component directory for foundation context
   * Format per line: label | type | zone | receives from: Component1 (via edge-code) | sends to: Component2 (via edge-code)
   * @param {number} maxAdjacent - max neighbour components to include per direction
   * @returns {string[]} Array of directory lines
   */
  getComponentDirectory(maxAdjacent = 2) {
    const directory = [];

    this.nodeIndex.forEach((node, nodeId) => {
      if (node.type === 'securityZone') return; // skip zone containers
      if (node.type === 'freehand' || node.type === 'shape' || node.type === 'textAnnotation') return; // skip drawing nodes

      const label = (node.data?.label || '').replace(/\n/g, ' ');
      const type = node.type;
      const zone = node.data?.zone || 'Unknown';
      const nodeCode = this.nodeToCode.get(nodeId) || 'unknown';

      let line = `${label} | ${type} | ${zone} | code: ${nodeCode}`;

      // NEW: include key metadata so AI can answer component-specific questions
      const vendor = node.data?.vendor ? `vendor: ${node.data.vendor}` : null;
      const product = node.data?.product ? `product: ${node.data.product}` : null;
      const version = node.data?.version ? `version: ${node.data.version}` : null;
      const metaParts = [vendor, product, version].filter(Boolean);
      if (metaParts.length > 0) {
        line += ` | ${metaParts.join(' | ')}`;
      }

      if (maxAdjacent > 0) {
        const connections = this.getNodeConnections(nodeId);
        const inbound = [];
        const outbound = [];

        connections.inbound.forEach(edge => {
          if (!edge) return;
          const sourceNode = this.nodeIndex.get(edge.source);
          const edgeCode = this.edgeToCode.get(edge.id) || 'unknown';
          if (sourceNode && sourceNode.data?.label) {
            inbound.push(`${sourceNode.data.label} (via ${edgeCode})`);
          }
        });

        connections.outbound.forEach(edge => {
          if (!edge) return;
          const targetNode = this.nodeIndex.get(edge.target);
          const edgeCode = this.edgeToCode.get(edge.id) || 'unknown';
          if (targetNode && targetNode.data?.label) {
            outbound.push(`${targetNode.data.label} (via ${edgeCode})`);
          }
        });

        // Add connection info with directionality and edge codes
        const connectionParts = [];
        if (inbound.length > 0) {
          const inList = inbound.slice(0, maxAdjacent).join(', ');
          connectionParts.push(`receives from: ${inList}`);
        }
        if (outbound.length > 0) {
          const outList = outbound.slice(0, maxAdjacent).join(', ');
          connectionParts.push(`sends to: ${outList}`);
        }
        
        if (connectionParts.length > 0) {
          line += ` | ${connectionParts.join(' | ')}`;
        }
      }

      directory.push(line);
    });

    return directory;
  }
}

module.exports = DiagramIndexReader;